name: tourismapp
description: "tourism app created for UJK BNSP JMP by Mohammad Hilmi Bisri"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.6.2
  
  # UI Components
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  
  # Utilities
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  sensors_plus: ^6.1.1
  internet_connection_checker: ^3.0.1


  # Date and Time
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/